---
title: "DESeq2_buffa"
author: "Rebecca Hoyd"
date: "2/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(DESeq2)
library(rlist)
library(glmm)
library(broom)
```

# Load data

```{r}
BHscores <- read.csv("/fs/ess/PAS1695/projects/HNSC/data/hnsc_buffa.csv",
                     stringsAsFactors = F)
HPVstatus <- read.csv("../data/HPV-prevalence-per-sample.csv",
                      stringsAsFactors = F)

exora <- read.csv("/fs/ess/PAS1695/projects/HNSC/data/drake-output/7-15-2021/7-15-2021_tcga_exora-with-taxonomy.csv", stringsAsFactors = F)
clin <- read.csv("/fs/ess/PAS1695/projects/HNSC/data/drake-output/7-15-2021/7-15-2021_tcga_clinical.csv", 
                 stringsAsFactors = F) 
```

# Define HSNC locations

```{r}
oropharynx.class <- c("Base of tongue", "Oropharynx", "Palate", "Tonsil")
oralcavity.class <- c("Floor of mouth", "Gum", "Lip",
                      "Other and ill-defined sites in lip, oral cavity and pharynx",
                      "Other and unspecified parts of mouth",
                      "Other and unspecified parts of tongue")
larhypopharynx.class <- c("Hypopharynx", "Larynx")

def.loc <- clin %>%
  select(file_id.BAM, file_id.expression, primary_site) %>%
  mutate(LocClass = case_when(primary_site %in% oropharynx.class ~ "Oropharynx",
                              primary_site %in% oralcavity.class ~ "OralCavity",
                              primary_site %in% larhypopharynx.class ~
                                "LarynxHypopharynx")) %>%
  filter(!is.na(LocClass))

exora <- exora %>%
  filter(sample %in% def.loc$file_id.BAM)
```

# Format

```{r function for getting count data}
taxaranks <- function(x) {
  
  res <- exora %>%
    select(c("sample", x, "exo.ra")) %>%
    as.data.frame() %>%
    group_by_at(c("sample",x)) %>%
    summarise(rel_abd = sum(exo.ra, na.rm = T)) %>%
    mutate(rel_abd = round(rel_abd*1e8)) %>%
    spread(key = "sample", value = "rel_abd") %>%
    column_to_rownames(var = x)

  return(res)
}
```

```{r formatting to wide matrices}
taxlevs <- c("domain","kingdom", "phylum", "class",
             "order", "family", "genus", "species")

count.matrices <- lapply(taxlevs, function(y) taxaranks(y))
names(count.matrices) <- taxlevs

identical(colnames(count.matrices[[1]]), colnames(count.matrices[[2]]))
```

```{r manipulate clinical data}
meta <- BHscores %>%
  rename("sample" = "file_id.expression") %>%
  inner_join(def.loc) %>%
  mutate(sample = file_id.BAM) %>%
  inner_join(HPVstatus) %>%
  mutate(buffa.tert = case_when(buffa.score < quantile(buffa.score, .3333) ~ 0,
                                 buffa.score > quantile(buffa.score, .6666) ~ 1),
         HPV.prev = ifelse(HPV.prev == 1, "Y", "N"))

countmat.ord <- data.frame(sample = colnames(count.matrices[[1]]))

meta <- countmat.ord %>%
  left_join(meta) 
  
identical(meta$sample, colnames(count.matrices[[1]]))

```

# Note mean buffa per location group

```{r}
meta %>%
  group_by(LocClass) %>%
  summarise(mean.buffa = mean(buffa.score),
            sd.buffa = sqrt(var(buffa.score)))
```

# DESeq

```{r run for HPV}
HPV.dds.ls <- lapply(count.matrices, function(x) DESeqDataSetFromMatrix(
  countData = x,
  design = ~HPV.prev,
  colData = meta)
  )

HPV.dds.ls <- lapply(HPV.dds.ls, function(x) DESeq(x))

HPV.res <- lapply(HPV.dds.ls, function(x) results(x) %>%
                    as.data.frame %>%
                    rownames_to_column(var = "taxa")) %>%
  bind_rows() %>%
  mutate(test.var = "HPV")
```

```{r run for BH}
# We have to remove NAs ourselves, deseq2 does not handle that
BH.good <- !is.na(meta$buffa.tert)
meta.BH <- meta[BH.good,]
BH.mats <- lapply(count.matrices, function(x) x[,BH.good])

BH.dds.ls <- lapply(BH.mats, function(x) DESeqDataSetFromMatrix(
  countData = x,
  design = ~buffa.tert,
  colData = meta.BH)
  )

BH.dds.ls <- lapply(BH.dds.ls, function(x) DESeq(x))

BH.res <- lapply(BH.dds.ls, function(x) results(x) %>%
                    as.data.frame %>%
                    rownames_to_column(var = "taxa")) %>%
  bind_rows() %>%
  mutate(test.var = "BH")
```

# Table results

```{r}
all.res <- bind_rows(HPV.res, BH.res)
write.csv(all.res, "../data/DESeq_BH-HPV.csv",
          row.names = F)

table.input <- all.res %>%
  mutate(sig = ifelse(padj < 0.05, 1, 0),
         direction = ifelse(sig == 0|is.na(sig), "None",
                            ifelse(log2FoldChange >= 0, "High", "Low"))) %>%
  select(taxa, test.var, direction) %>%
  spread(key = "test.var", value = "direction")

table.res <- table.input %>%
  group_by(BH, HPV) %>%
  tally()
```

```{r}
table.res %>%
  mutate(HPV = paste0("HPV.", HPV)) %>%
  spread(key = "HPV", value = "n") 
```

# Repeat for multivariate, location classes

```{r}
capture.models.univ <- function(outcome, lfun, modin){
  mods.list <- lapply(mics, function(x) try({glm(as.formula(paste0(outcome, " ~ `", x, "`")), family = lfun, data = modin) %>%
                        tidy()})
                      )
                      
  mods.list.clean <- list.clean(mods.list, function(x) is.null(x))
  mods.df <- bind_rows(mods.list.clean)
  return(mods.df)
}

capture.models.multi <- function(outcome, lfun, inters, modin){
  mods.list <- lapply(mics, function(x) try({glm(as.formula(paste0(outcome, " ~ `", x, "` + ", inters)), family = lfun, data = modin) %>%
      tidy() %>%
      mutate(microbe = x)})
  )
  
  mods.list.clean <- list.clean(mods.list, function(x) is.null(x))
  mods.df <- bind_rows(mods.list.clean)
  return(mods.df)
}
```

## Formatting

```{r}
allmics.data  <- bind_rows(lapply(BH.mats, 
                                  function(x) rownames_to_column(x,var = "taxa"))) %>%
  gather(-taxa, key = "sample", value = "RA") %>%
  spread(key = taxa, value = RA)

BH.in <- meta.BH %>%
  left_join(allmics.data)

mics <- colnames(allmics.data[,-1])

OC.in <- BH.in %>%
  filter(LocClass == "OralCavity")
OP.in <- BH.in %>%
  filter(LocClass == "Oropharynx")
LH.in <- BH.in %>%
  filter(LocClass == "LarynxHypopharynx")
```
## Single variable location classes

```{r, warning=FALSE}
OC.res <- capture.models.univ("buffa.tert", "binomial", OC.in) %>%
  filter(term != "(Intercept)")
OP.res <- capture.models.univ("buffa.tert", "binomial", OP.in) %>%
  filter(term != "(Intercept)")
LH.res <- capture.models.univ("buffa.tert", "binomial", LH.in) %>%
  filter(term != "(Intercept)")
```

## Multi variable location classes

```{r, warning=FALSE}
OP.mult <- capture.models.multi("buffa.tert", "binomial", "HPV.prev", OP.in) %>%
  filter(grepl("HPV", term))
```

## Save results

```{r}
write.csv(OC.res, "../data/modelling_binom_OralCavity.csv", row.names = F)
write.csv(OP.res, "../data/modelling_binom_Oropharynx.csv", row.names = F)
write.csv(LH.res, "../data/modelling_binom_LarynxHypopharinx.csv", row.names = F)

write.csv(OP.mult, "../data/modelling_binom_inter_Oropharynx.csv", row.names = F)
```
