---
title: "exorien introductory meeting"
author: "Rebecca Hoyd"
date: "9/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(survival)
library(survminer)
library(ggplot2)
library(tibble)
library(tidyr)
library(Hmisc)
library(ggforce)
library(forcats)
```

# Functions

```{r}
extract_coxph_results <- function(cp.form, dattab){
    tmp <- coxph(as.formula(cp.form), data = dattab) %>%
      summary()
  pvals <- tmp$coefficients %>%
    as.data.frame() %>%
    rownames_to_column(var = "term") %>%
    mutate(p.value = `Pr(>|z|)`) %>%
    select(term, p.value)
  conf.int <- tmp$conf.int %>%
    as.data.frame() %>%
    rownames_to_column(var = "term") %>%
    mutate(hazard.ratio = `exp(coef)`,
           confint.low = `lower .95`,
           confint.high = `upper .95`) %>%
    select(term, hazard.ratio, confint.low, confint.high) %>%
    left_join(pvals) 
  return(conf.int)
}


get_king_ra <- function(exora, sampcol){
  exora$sample <- exora[[sampcol]]
  exora.king <- exora %>%
  filter(microbe != "Homo.sapiens") %>%
  group_by(sample) %>%
  mutate(tot.ra = sum(exo.ra),
         exo.ra = exo.ra/tot.ra) %>%
  ungroup() %>%
  group_by(sample, kingdom) %>%
  summarise(ra = sum(exo.ra, na.rm = T)) %>%
  as.data.frame()
}

get_samp_ord <- function(exoking, desking){
  tmp <- exoking %>%
    filter(kingdom == desking) %>%
    arrange(desc(ra))
  
  return(tmp$sample)
}

stacked_plotting <- function(exoking, knames, sord, addit.dat){
  exoking %>%
    mutate(kingdom = ifelse(kingdom %in% knames, kingdom, "Other"),
           kingdom = gsub("^k__", "", kingdom),
           kingdom = gsub("unclassified-\\w__", "", kingdom)) %>%
  group_by(sample, kingdom) %>%
  summarise(ra = sum(ra, na.rm = T)) %>%
    left_join(addit.dat) %>%
    ggplot(aes(x = fct_relevel(sample, sord),
               y = ra, 
               fill = kingdom
    ))+
    geom_bar(position="fill", stat = "identity") +
    labs(x = "", y = "") +
    scale_fill_brewer(palette = "Dark2", name = "Taxa") +
    theme_minimal() +
    theme(axis.text.x = element_blank(), 
          axis.ticks.x = element_blank(),
          axis.text.y = element_blank(),
          panel.grid.major = element_blank())
}
```

# Load data
```{r}
data.dir <- "/fs/ess/PAS1695/projects/HNSC/data/drake-output/7-15-2021"

clin <- read.csv(file.path(data.dir, "7-15-2021_tcga_clinical.csv"), stringsAsFactors = F)
exora <- read.csv(file.path(data.dir, "7-15-2021_tcga_exora-with-taxonomy.csv"), stringsAsFactors = F)

rarprev <- read.csv("../data/rarefied-prevalence_all-TCGA-samps.csv")

```

# Survival

```{r}
surv.in <- clin %>%
  rename("sample" = "file_id.BAM") %>%
  inner_join(rarprev) %>%
  mutate(smoking = ifelse(pack_years_smoked >= 10, 1, 0),
         smoking = ifelse(is.na(smoking), 0, smoking),
         age = age_at_diagnosis/365.25,
         days = coalesce(days_to_death, days_to_last_follow_up),
         vitalstatus = ifelse(vital_status == "Dead", 1, 0),
         survstage = ifelse(grepl("IV", ajcc_clinical_stage), "Stage IV", ajcc_clinical_stage)) %>%
  drop_na(days, vitalstatus)
```

```{r}
alphapap.mod <- survfit(Surv(days, vitalstatus) ~ Alphapapillomavirus.9, data = surv.in)
alphapap.cox <- extract_coxph_results("Surv(days, vitalstatus) ~ Alphapapillomavirus.9 + smoking + age + survstage",
                                      surv.in)
ggsurvplot(alphapap.mod, pval = T) +
  ggsave("../figures/exorien_KM-curve.png")

alphapap.cox %>%
  mutate(vargroup = ifelse(grepl("survstage", term), "Stage", capitalize(term)),
         term = capitalize(gsub("survstage", "", term)),
         term = fct_relevel(term, "Alphapapillomavirus.9", after = 5)) %>%
  ggplot(aes(x = term, xend = term)) +
  geom_point(aes(y = hazard.ratio)) +
  geom_segment(aes(y = confint.low, yend = confint.high)) +
  labs(x = "", y = "Hazard Ratio") + 
  coord_flip() +
  geom_hline(yintercept = 1, lty = 2) +
  # facet_col(vars(vargroup), space = "free", scales = "free_y", strip.position = "left") +
  theme_bw() +
  ggsave("../figures/exorien_forestplot.png", width = 5, height = 5)
```

# Stacked bar

```{r}
hpv.sata <- rarprev %>%
  select(sample, Alphapapillomavirus.9)

exo.k <- get_king_ra(exora, "sample")

large.k <-  exo.k %>% 
  group_by(kingdom) %>%
  summarise(median.ra = median(ra)) %>%
  arrange(desc(median.ra)) %>%
  mutate(x = row_number()) %>%
  filter(x <= 7) %>%
  select(kingdom)

k.sampord <- get_samp_ord(exo.k, "k__unclassified-o__Ortervirales")
```

```{r}
stacked_plotting(exo.k, large.k$kingdom, k.sampord, hpv.sata) +
  facet_row(vars(Alphapapillomavirus.9), scales = "free_x", space = "free") +
  ggsave("../figures/exorien_stacked-bar.png", height = 5, width = 5)
```

# SITC: Dense forest