---
title: "fig1 - buffa 2.0"
author: "Caroline Wheeler"
date: "4/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readr)
library(tidyr)
library(ggplot2)
library(Hmisc)
library(plyr)
library(RColorBrewer)
library(reshape2)
library(PupillometryR)
source("00-paths.R")
```

read in R object w/ buffa scores for all cancer and HNSC location 
```{r}
comb <- readRDS(file.path(paths$mitoscore, "/data/buffa-mitophagy_tcga-cancer.RData"))
loc <- read.csv("../data/location.csv")

comb <- merge(comb, loc, by="sampleID", all = T) %>%
  select(-X) %>%
  mutate(LocClass = ifelse(is.na(LocClass), "Other", LocClass))
```

```{r}
mean.buffa <- 
  comb %>%
  dplyr::group_by(cancer) %>%
  dplyr::summarize(mean = mean(BUFFA_HYPOXIA_SCORE)) %>%
  mutate(`Buffa Category` = if_else(mean > 0,
                             true = "HB",
                             false = "LB")) %>%
  mutate(cancer = fct_reorder(cancer, mean))
```

```{r}
comb.ord <- 
  comb %>%
  left_join(mean.buffa) %>%
  mutate(cancer = fct_reorder(cancer, -mean))
```

```{r}
comb.ord %>%
  ggplot(aes(y = BUFFA_HYPOXIA_SCORE, x = cancer)) + 
  geom_flat_violin(position = position_nudge(x = .2, y = 0), alpha = .8) +
  geom_point(aes(y = BUFFA_HYPOXIA_SCORE, color = LocClass), position = position_jitter(width = .15), size = .5, alpha = 0.8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  expand_limits(x = 5.25) +
  guides(fill = FALSE) +
  guides(color = FALSE) +
  scale_color_manual(values = c(muted("rosybrown"), "cornflowerblue", "yellow3" ,"gray50")) +
  #scale_fill_viridis_d() +
  coord_flip() +
  theme_bw() 

ggsave("../figures/buffa-cancer-raincloud2.0.png",
      height = 7, width = 5)
```




