---
title: "buffa-all cancers"
author: "Caroline Wheeler"
date: "4/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(colorspace)
library(scales)
library(svglite)
source("00-paths.R")
```

read in R object w/ buffa scores for all cancer and HNSC location 
```{r}
comb <- readRDS(file.path(paths$mitoscore, "/data/buffa-mitophagy_tcga-cancer.RData"))
loc <- read.csv("../data/location.csv")

comb <- merge(comb, loc, by="sampleID", all = T) %>%
  select(-X) %>%
  mutate(LocClass = ifelse(is.na(LocClass), "Other", LocClass)) %>%
  filter(!is.na(cancer)) %>%
  filter(!(cancer == "HNSC" & LocClass == "Other"))
```

```{r}
mean.buffa <- 
  comb %>%
  group_by(cancer) %>%
  summarize(mean = mean(BUFFA_HYPOXIA_SCORE)) %>%
  mutate(`Buffa Category` = if_else(mean > 0,
                             true = "HB",
                             false = "LB")) %>%
  mutate(cancer = fct_reorder(cancer, mean))
```

```{r}
comb.ord <- 
  comb %>%
  left_join(mean.buffa) %>%
  mutate(cancer = fct_reorder(cancer, -mean),
         resize = ifelse(cancer == "HNSC", "HNSC", "Other"))
```

```{r}
table_data <- comb.ord %>%
  select(BUFFA_HYPOXIA_SCORE, LocClass) %>%
  group_by(LocClass) %>%
  summarize(mean = mean(BUFFA_HYPOXIA_SCORE),
            sd = sd(BUFFA_HYPOXIA_SCORE))
```


```{r}
comb.ord %>%
  ggplot(aes(x = cancer, y = BUFFA_HYPOXIA_SCORE)) +
  
  scale_x_discrete(limits = rev) +
  
  facet_grid(vars(resize), scales = "free") +
  
    ggdist::stat_halfeye(
    aes(
      color = LocClass,
      fill = after_scale(lighten(color, .5))
    ),
    position = position_nudge(x = .2, y = 0),
    shape = 18,
    point_size = 3,
    interval_size = 1.8,
    adjust = .5,
    .width = c(0, 1),
    show.legend = FALSE
  ) +
  
  geom_point(
    aes(color = LocClass),
    position = position_jitter(width = .15,),
    size = 1,
    alpha = .5
  ) +

  theme_bw() +
  theme(
    panel.border = element_blank(),
    strip.text = element_blank(),
   panel.spacing = unit(0, "lines")) +
  coord_flip() +
  scale_color_manual(values = c(muted("rosybrown"), "cornflowerblue", "yellow3" ,"gray50")) +
  labs(y = "Hypoxia Score",
       x = "") 

ggsave("../figures/fig1_buffa-cancer-raincloud.png",
     height = 7, width = 6)
ggsave("../figures/fig1_buffa-cancer-raincloud.svg",
      height = 7, width = 6)
```
```{r}
comb.ord %>%
  ggplot(aes(x = cancer, y = BUFFA_HYPOXIA_SCORE)) +
  
  scale_x_discrete(limits = rev) +
  
  facet_grid(vars(resize), scales = "free") +
  
    geom_point(
    aes(color = LocClass),
    position = position_jitter(width = .15,),
    size = 1,
    alpha = .5
  ) +
  
    ggdist::stat_halfeye(
    aes(
      fill = LocClass
    ),
    position = position_nudge(x = .2, y = 0),
    shape = 18,
    alpha = .5,
    point_size = 3,
    interval_size = 1.8,
    adjust = .5,
    .width = c(0, 1),
    show.legend = FALSE
  ) +
  
  theme_bw() +
  theme(
    panel.border = element_blank(),
    strip.text = element_blank(),
   panel.spacing = unit(0, "lines")) +
  coord_flip() +
  scale_color_manual(values = c(muted("rosybrown"), "cornflowerblue", "yellow3" ,"gray50")) +
  scale_fill_manual(values = c("rosybrown", "cornflowerblue", "yellow3" ,"gray50")) +
  labs(y = "Buffa Hypoxia Score",
       x = "") 

ggsave("../figures/fig1_buffa-cancer-raincloud_v2.png",
     height = 7, width = 6)
ggsave("../figures/fig1_buffa-cancer-raincloud_v2.svg",
      height = 7, width = 6)
```

