---
title: "fig1"
author: "Caroline Wheeler"
date: "4/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(forcats)
library(ggforce)
library(patchwork)
```

# Load data

```{r}
BHscores <- read.csv("/fs/ess/PAS1695/projects/HNSC/data/hnsc_buffa.csv") %>%
  rename("file_id.expression" = sample)

exora <- read.csv("/fs/ess/PAS1695/projects/HNSC/data/drake-output/7-15-2021/7-15-2021_tcga_exora-with-taxonomy.csv", stringsAsFactors = F)
clin <- read.csv("/fs/ess/PAS1695/projects/HNSC/data/drake-output/7-15-2021/7-15-2021_tcga_clinical.csv", 
                 stringsAsFactors = F) 
```


# Define HSNC locations

```{r}
oropharynx.class <- c("Base of tongue", "Oropharynx", "Palate", "Tonsil")
oralcavity.class <- c("Floor of mouth", "Gum", "Lip",
                      "Other and ill-defined sites in lip, oral cavity and pharynx",
                      "Other and unspecified parts of mouth",
                      "Other and unspecified parts of tongue")
larhypopharynx.class <- c("Hypopharynx", "Larynx")

def.loc <- clin %>%
  select(file_id.BAM, file_id.expression, primary_site) %>%
  mutate(LocClass = case_when(primary_site %in% oropharynx.class ~ "Oropharynx",
                              primary_site %in% oralcavity.class ~ "Oral Cavity",
                              primary_site %in% larhypopharynx.class ~
                                "Larynx/Hypopharynx")) %>%
  filter(!is.na(LocClass)) %>%
  rename("sample" = file_id.BAM)

exora <- exora %>%
  filter(sample %in% def.loc$sample)

def.loc <- merge(def.loc, BHscores)
```


```{r}
get_phyl_ra <- function(exora){
  exora.phyl <- exora %>%
  filter(microbe != "Homo.sapiens") %>%
  group_by(sample, phylum) %>%
  summarise(ra = sum(exo.ra, na.rm = T)) %>%
  as.data.frame()
}
```

```{r}
exora <- exora%>%
  filter(!is.na(phylum))

exora.p <- get_phyl_ra(exora)

large.phyls <- exora.p %>% 
  group_by(phylum) %>%
  summarize(median.ra = median(ra)) %>%
  arrange(desc(median.ra)) %>%
  mutate(x = row_number()) %>%
  dplyr::filter(x <= 7)
large.phyls <- large.phyls$phylum
tmp <- exora.p %>% arrange(desc(ra))
sampord.orter <- tmp$sample
```

combine with location data
```{r}
exora.p.hist <- merge(exora.p, def.loc)
```

```{r}
exora.p.hist <- exora.p.hist %>%
  mutate(phylum = ifelse(phylum %in% large.phyls, phylum, "Other"),
         phylum = gsub("^p__", "", phylum),
         phylum = ifelse(phylum == "unclassified-o__Ortervirales", "Ortervirales", 
         ifelse(phylum == "unclassified-o__Caudovirales", "Caudovirales", phylum)))
```


Plot
```{r}
exora.p.hist <- exora.p.hist[order(exora.p.hist$buffa.score),]
exora.p.hist <- exora.p.hist %>%
  

g <- exora.p.hist %>% 
  ggplot(aes(x = sample, y = ra, fill = phylum)) +
    geom_bar(position="fill", stat = "identity") +
    labs(x = "", y = "") +
    scale_fill_manual(values = c("darkslateblue","red3", "darkgoldenrod2", "darkgreen", "darkorange4","salmon2", "cornflowerblue", "deeppink4" ,"cyan4", "salmon2"), name = "Taxa") +
    theme_minimal(base_size = 18) +
    theme(axis.text.x = element_blank(), 
          axis.ticks.x = element_blank(),
          axis.text.y = element_blank(),
          panel.grid.major = element_blank())  +
   facet_row(vars(LocClass), scales = "free_x", space = "free") 
g

ggsave(g, file = "../exploratory/figures/fig1_stackedbar.png", dev = "png", width = 13, height = 13)
```





