---
title: "buffa hypoxia score"
author: "Caroline Wheeler"
date: "2/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tmesig)
library(tibble)
```

read in data
```{r}
genes <- read.csv("/fs/ess/PAS1695/projects/HNSC/data/drake-output/7-26-2021/7-26-2021_tcga_gene-expressions_norm.csv")

```

prep dataframe
```{r}
gene_list <- colnames(genes)

rownames(genes) <- genes$sample 
genes <- genes %>% select(-sample)

genes <- as.data.frame(t(genes)) 
genes <- tibble::rownames_to_column(genes, "Gene")
```

Check for missing genes
```{r}
buffa.genes <- inputGenes("Buffa")
checkGenes(gene_list, "Buffa")
```

make corrected gene list
```{r}
revised.genes <- c("UTP11", "PNP", "HILPDA", "DDRGK1", "AK3", "ESRP1", "CTSV")
```


calculate buffa score
```{r}
buffa.out <- calculateBuffa(genes, c(inputGenes("Buffa"), revised.genes))
```

```{r}
write.csv(buffa.out, row.names = F, "/fs/ess/PAS1695/projects/HNSC/data/hnsc_buffa.csv")
```

