---
title: "Volcano Plot for DEGs"
author: "Malven"
date: "10/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggrepel)
library(dplyr)
```

# Load DEGs
```{r}
HPV_deseq.genes <- read.table("../data/HPV_deseq.genes.txt", header = T)

```

# Volcano Plot & Box Plot
```{r}
# Volcano Plot

hpv.volc.dat <- HPV_deseq.genes %>%
  mutate(diffexp = ifelse(log2FoldChange > 2.5 & pvalue < 0.05, yes = "UP",
                   ifelse(log2FoldChange < -2.5 & pvalue < 0.05, yes = "DOWN", no = NA))) %>%
  mutate(diffexp = ifelse(is.na(diffexp), yes = "NO", no = diffexp))

hpv.volc.dat %>%
  ggplot(aes(x = log2FoldChange, y = -log10(pvalue), col = diffexp)) +
  geom_point() +
  geom_text_repel(data=subset(hpv.volc.dat, log2FoldChange < -3.5 | log2FoldChange > 3.5),
                        aes(x = log2FoldChange, y = -log10(pvalue), label = Genes),
                  colour = "black", size = 2.5, fontface= 2, box.padding = 1.0, max.overlaps = Inf) +
  geom_hline(yintercept = 0.05, color = "red", linetype = 2) +
  geom_vline(xintercept = c(-2.5,2.5), color = "red", linetype = 2) +
  scale_color_manual( breaks = c("UP", "DOWN", "NO"),
                      values = c("orange", "purple", "grey"),
                      label  = c("Enriched", "Depleted", "Not Significant"),
                      name   = "Genes")+
  ggtitle("HPV - Positive vs Negative") +
  theme(legend.key.size = unit(0.5, 'cm'),
        legend.title = element_text(size=10),
        legend.text = element_text(size=10)) +
  theme_bw()

ggsave("../figures/volcano_differential-gene-expression.png", width = 7, height = 6, device = "png")
```
