---
title: "volcano_plot-differentially-expressed-microbes"
author: "Malven"
date: "10/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(ggrepel)
library(dplyr)
```

# Load DEMs
```{r}

HPV_deseq.microbes <- read.table("../data/HPV_deseq.microbes.txt", quote = "", sep="\t", header = TRUE) 

```

# Volcano Plot
```{r}
# Volcano Plot

hpv.volc.dat <- HPV_deseq.microbes %>%
  mutate(diffexp = ifelse(log2FoldChange > 1.0 & pvalue < 0.05, yes = "UP",
                   ifelse(log2FoldChange < -1.0 & pvalue < 0.05, yes = "DOWN", no = NA))) %>%
  mutate(diffexp = ifelse(is.na(diffexp), yes = "NO", no = diffexp)) %>%
  mutate(tax_class = ifelse(log2FoldChange > 1.0 & -log10(pvalue) > 3, yes = tax_class,
                     ifelse(log2FoldChange < -1.0 & -log10(pvalue) > 3, yes = tax_class, no = NA))) %>%
  mutate(tax_class = ifelse(is.na(tax_class), yes = "NO", no = tax_class)) 

tax.labels <- hpv.volc.dat %>%
  subset(log2FoldChange < -1.0 | log2FoldChange > 1.0) %>%
  subset(-log10(pvalue) > 3)
  
hpv.volc.dat %>%
  ggplot(aes(x = log2FoldChange, y = -log10(pvalue), col = diffexp)) +
  geom_point(data= hpv.volc.dat, aes(x=log2FoldChange, y=-log10(pvalue), color= tax_class),size=2) +
  geom_text_repel(data = tax.labels, aes(x = log2FoldChange, y = -log10(pvalue), label = Taxonomy),
                  colour = "black", size = 2, fontface= 1, box.padding = 1.0, max.overlaps = Inf) +
  geom_hline(yintercept = 3, color = "red", linetype = 2) +
  geom_vline(xintercept = c(-1.0,1.0), color = "red", linetype = 2) +
  scale_color_manual( breaks = c("class", "family", "genus", "kingdom", "order", "phlyum", "species", "NO"),
                      values = c("orange", "purple", "blue", "green", "red", "yellow", "pink", "grey"),
                      label  = c("class", "family", "genus", "kingdom", "order", "phlyum", "species", "not significant"),
                      name   = "Taxa") +
  theme_bw() 
 

ggsave("../figures/volcano_differentially-expressed-microbes.png", width = 8, height = 8, device = "png")
```
  
